#!/bin/bash

[ ! -d /magento-app ] && echo -e "ERR~ /magento-app folder not found" && exit 1
cd /magento-app
[ ! -f bin/magento ] && echo -e "ERR~ No magento app at /magento-app" && exit 1
rm -rfv var/view_preprocessed/*
rm -rfv pub/static/*/*
rm -rfv generated/*/*
bin/magento setup:di:compile
bin/magento cache:flush
