#!/bin/bash

# 0. Define target branch
declare target_branch=develop
[ -n "${1}" ] && target_branch="${1}"

# 1. Validate path
[ ! -d /magento-app ] && echo -e "ERR~ /magento-app folder not found" && exit 1
[ ! -f /magento-app/bin/magento ] && echo -e "ERR~ No magento app at /magento-app folder" && exit 1

# 2. Move to deliver path
cd /magento-app

# 3. Update repository
bin/magento maintenance:enable
git restore .
git fetch
git switch "${target_branch}"
git pull

# 4. Update dependencies
composer i
git restore .

# 5. Deliver changes
bin/magento app:config:import
bin/magento setup:upgrade
bin/magento setup:di:compile

# 6. Finish
bin/magento cache:flush
bin/magento maintenance:disable
