#!/bin/bash

# 0. Get params
declare target_dir="."
declare target_branch=develop
while [ -n "${1}" ]; do
  if [ "${1}" = "-d" ]; then
    [ -z "$(echo "${2}" | grep "^-")" ] && target_dir="${2}" && shift
  elif [ "${1}" = "-b" ]; then
    [ -z "$(echo "${2}" | grep "^-")" ] && target_branch"${2}" && shift
  fi
  shift
done
[ -n "$(echo "${target_dir}" | grep "/$")" ] && target_dir="${target_dir::-1}"

# 1. Validate path
[ ! -d "${target_dir}" ] && echo -e "ERR~ target directory '${target_dir}' doesn't exists" && exit 1
[ ! -f "${target_dir}/bin/magento" ] && echo -e "ERR~ No magento app found at '${target_dir}'" && exit 1
echo -e "INF~ MAGEDELIVER at '${target_dir}' for branch '${target_branch}'"

# 2. Move to deliver path
cd "${target_dir}"

# 3. Update repository
bin/magento maintenance:enable
git restore .
git fetch
git switch "${target_branch}"
git pull

# 4. Update dependencies
composer i
git restore .

# 5. Deliver changes
bin/magento app:config:import
bin/magento setup:upgrade
bin/magento setup:di:compile

# 6. Finish
bin/magento indexer:reindex
bin/magento cache:flush
bin/magento maintenance:disable
