#!/bin/bash

# 0. Get params
declare target_dir="."
while [ -n "${1}" ]; do
  if [ "${1}" = "-d" ]; then
    [ -z "$(echo "${2}" | grep "^-")" ] && target_dir="${2}" && shift
  fi
  shift
done
[ -n "$(echo "${target_dir}" | grep "/$")" ] && target_dir="${target_dir::-1}"

# 1. Validate path
[ ! -d "${target_dir}" ] && echo -e "ERR~ target directory '${target_dir}' doesn't exists" && exit 1
[ ! -f "${target_dir}/bin/magento" ] && echo -e "ERR~ No magento app found at '${target_dir}'" && exit 1
echo -e "INF~ MAGECLEAN at '${target_dir}'"

# 2. Move to app path
cd "${target_dir}"

# 3. Remove files
rm -rfv var/view_preprocessed/*
rm -rfv pub/static/*/*
rm -rfv generated/*/*

# 4. Finish
bin/magento setup:di:compile
bin/magento cache:flush
