#!/bin/bash

# 0. Get params
declare target_dir="."
declare target_branch=develop
while [ -n "${1}" ]; do
  if [ "${1}" = "-d" ]; then
    [ -z "$(echo "${2}" | grep "^-")" ] && target_dir="${2}" && shift
  elif [ "${1}" = "-b" ]; then
    [ -z "$(echo "${2}" | grep "^-")" ] && target_branch="${2}" && shift
  fi
  shift
done
[ -n "$(echo "${target_dir}" | grep "/$")" ] && target_dir="${target_dir::-1}"

# 1. Validate path
echo -e "\nINF~ MAGEDELIVER (1/6) Checking directories...\n"
[ ! -d "${target_dir}" ] && echo -e "ERR~ target directory '${target_dir}' doesn't exists" && exit 1
[ ! -f "${target_dir}/bin/magento" ] && echo -e "ERR~ No magento app found at '${target_dir}'" && exit 1
echo -e "\nINF~ MAGEDELIVER (1/6) All right at '${target_dir}' for branch '${target_branch}'\n"

# 2. Move to deliver path
echo -e "\nINF~ MAGEDELIVER (2/6) Moving to deliver folder...\n"
cd "${target_dir}"
echo -e "\nINF~ MAGEDELIVER (2/6) Ready to start delivering\n"

# 3. Update repository
echo -e "\nINF~ MAGEDELIVER (3/6) Updating repository...\n"
bin/magento maintenance:enable
git restore .
git fetch
git switch "${target_branch}"
git pull
echo -e "\nINF~ MAGEDELIVER (3/6) All updated!\n"

# 4. Update dependencies
echo -e "\nINF~ MAGEDELIVER (4/6) Updating dependencies...\n"
composer i
git restore .
echo -e "\nINF~ MAGEDELIVER (4/6) All updated!\n"

# 5. Deliver changes
echo -e "\nINF~ MAGEDELIVER (5/6) Delivering changes...\n"
bin/magento app:config:import
bin/magento setup:upgrade
bin/magento setup:di:compile
echo -e "\nINF~ MAGEDELIVER (5/6) Changes delivered!\n"

# 6. Finish
echo -e "\nINF~ MAGEDELIVER (6/6) Executing last task...\n"
bin/magento indexer:reindex
bin/magento cache:flush
bin/magento maintenance:disable
echo -e "\nINF~ MAGEDELIVER (6/6) All done!\n"
